# Generated by Django 5.0 on 2024-10-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FetalHealthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LBE', models.IntegerField()),
                ('LB', models.IntegerField()),
                ('AC', models.IntegerField()),
                ('FM', models.IntegerField()),
                ('UC', models.IntegerField()),
                ('ASTV', models.IntegerField()),
                ('MSTV', models.IntegerField()),
                ('ALTV', models.IntegerField()),
                ('MLTV', models.IntegerField()),
                ('DL', models.IntegerField()),
                ('DS', models.IntegerField()),
                ('DP', models.IntegerField()),
                ('DR', models.IntegerField()),
                ('Width', models.IntegerField()),
                ('Min', models.IntegerField()),
                ('Max', models.IntegerField()),
                ('Nmax', models.IntegerField()),
                ('Nzeros', models.IntegerField()),
                ('Mode', models.IntegerField()),
                ('Mean', models.IntegerField()),
                ('Median', models.IntegerField()),
                ('Variance', models.IntegerField()),
                ('Tendency', models.IntegerField()),
                ('SUSP', models.IntegerField()),
                ('CLASS', models.IntegerField()),
                ('label', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='DiabetesAssessment',
        ),
    ]
